### ISSUE TITLE
SPLIT_PENALTY_MATCHING_BRACKET error with yapf 0.2.5

### ISSUE THREAD

**Issue by donnex** [jason-kane/PyYapf#10]
When I installed the latest version of yapf (0.2.5) I got the following error when running Yapf format in Sublime.

```
yapf

Unknown style option "SPLIT_PENALTY_MATCHING_BRACKET"

{}
```

**Comment by jason-kane** [comment]
It should now be cleared up; thank you Donnex.  I need to do a little research and see what all the now-valid options are but in the meantime this one is commented out.

Long term there is no realistic way to stay locksetup synced with yapf, maybe try and encourage them to warn/ignore instead of fail when they get an unexpected config setting.

**Comment by donnex** [comment]
Hello again, I just updated my Sublime packages today and got a new version of the yapf plugin. But I'm still seeing this exact error message.

Do I have to install this plugin manually to get the update with the fix?

I'm using Package Control in Sublime and when I list packages it tells me that I've got v. 0.7.0 installed of PyYapf.

Thanks for your help :)

**Comment by jason-kane** [comment]
Oop, I have to release a new version for package control to pick it up.
I'll push out a 0.8 today.

**Comment by donnex** [comment]
Sweet! I'll give you a shout if it's working with the new version :)

**Comment by jason-kane** [comment]
0.8.1 is out, I don't know how long it will take package control to pick it up.  I'm guessing a few hours.

**Comment by donnex** [comment]
It's available now and it's working great, thanks!
